package com.shuma.oneproject.infrastructure.data.main.repository.unitofwork.model;

public class AccountDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.id
     *
     * @mbg.generated Fri May 10 18:34:58 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.encrypted_password
     *
     * @mbg.generated Fri May 10 18:34:58 CST 2019
     */
    private String encryptedPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.password_salt
     *
     * @mbg.generated Fri May 10 18:34:58 CST 2019
     */
    private String passwordSalt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.id
     *
     * @return the value of tb_account.id
     *
     * @mbg.generated Fri May 10 18:34:58 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.id
     *
     * @param id the value for tb_account.id
     *
     * @mbg.generated Fri May 10 18:34:58 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.encrypted_password
     *
     * @return the value of tb_account.encrypted_password
     *
     * @mbg.generated Fri May 10 18:34:58 CST 2019
     */
    public String getEncryptedPassword() {
        return encryptedPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.encrypted_password
     *
     * @param encryptedPassword the value for tb_account.encrypted_password
     *
     * @mbg.generated Fri May 10 18:34:58 CST 2019
     */
    public void setEncryptedPassword(String encryptedPassword) {
        this.encryptedPassword = encryptedPassword == null ? null : encryptedPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.password_salt
     *
     * @return the value of tb_account.password_salt
     *
     * @mbg.generated Fri May 10 18:34:58 CST 2019
     */
    public String getPasswordSalt() {
        return passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.password_salt
     *
     * @param passwordSalt the value for tb_account.password_salt
     *
     * @mbg.generated Fri May 10 18:34:58 CST 2019
     */
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt == null ? null : passwordSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account
     *
     * @mbg.generated Fri May 10 18:34:58 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", encryptedPassword=").append(encryptedPassword);
        sb.append(", passwordSalt=").append(passwordSalt);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account
     *
     * @mbg.generated Fri May 10 18:34:58 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AccountDO other = (AccountDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEncryptedPassword() == null ? other.getEncryptedPassword() == null : this.getEncryptedPassword().equals(other.getEncryptedPassword()))
            && (this.getPasswordSalt() == null ? other.getPasswordSalt() == null : this.getPasswordSalt().equals(other.getPasswordSalt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_account
     *
     * @mbg.generated Fri May 10 18:34:58 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEncryptedPassword() == null) ? 0 : getEncryptedPassword().hashCode());
        result = prime * result + ((getPasswordSalt() == null) ? 0 : getPasswordSalt().hashCode());
        return result;
    }
}